### ISSUE TITLE
CSS Folder 만들기

### ISSUE THREAD

**Issue by seongdongwon1** [seongdongwon1/sign-up-system#7]
제가 이해한 바로는,

제가 사용하고 있는 editer 는 atom 입니다.

atom 에서는 css 파일을 따로 저장을 해서

html 파일에서 stylesheet 를 통해서 불러오기가 가능한데,

github 에서는 css파일과 html 파일을 업로드 하더라도

적용이 안된다. 

그래서 css folder , html folder 를 만들고 그 폴더안에 각각의 해당되는 파일들을 넣은 후

html stylesheet 명령어를        sign-up-system/CSS/signup.css

로 수정을 해야지 적용이 된다.

이렇게 제가 알려주신 link 와 검색엔진을 통해서 이해한 내용인데, 맞는지가 먼저 궁금합니다.

**Comment by seongdongwon1** [comment]
> 제가 이해한 바로는,
> 
> 제가 사용하고 있는 editer 는 atom 입니다.
> 
> atom 에서는 css 파일을 따로 저장을 해서
> 
> html 파일에서 stylesheet 를 통해서 불러오기가 가능한데,
> 
> github 에서는 css파일과 html 파일을 업로드 하더라도
> 
> 적용이 안된다.
> 
> 그래서 css folder , html folder 를 만들고 그 폴더안에 각각의 해당되는 파일들을 넣은 후
> 
> html stylesheet 명령어를 sign-up-system/CSS/signup.css
> 
> 로 수정을 해야지 적용이 된다.
> 
> 이렇게 제가 알려주신 link 와 검색엔진을 통해서 이해한 내용인데, 맞는지가 먼저 궁금합니다.

**Comment by jongfeel** [comment]
별다른 코멘트 없이 claosed를 한 이유가 있나요?
